// flow-typed signature: ee0a5b481e723a8e9602a2ceb25581c9
// flow-typed version: <<STUB>>/directory-named-webpack-plugin_v2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'directory-named-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'directory-named-webpack-plugin' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'directory-named-webpack-plugin/index' {
  declare module.exports: $Exports<'directory-named-webpack-plugin'>
}
declare module 'directory-named-webpack-plugin/index.js' {
  declare module.exports: $Exports<'directory-named-webpack-plugin'>
}
