// flow-typed signature: 2df343fb14a28d9253ab6762a2d2c428
// flow-typed version: <<STUB>>/inline-manifest-webpack-plugin_v^3.0.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inline-manifest-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inline-manifest-webpack-plugin' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'inline-manifest-webpack-plugin/index' {
  declare module.exports: $Exports<'inline-manifest-webpack-plugin'>
}
declare module 'inline-manifest-webpack-plugin/index.js' {
  declare module.exports: $Exports<'inline-manifest-webpack-plugin'>
}
