// flow-typed signature: d2330da0008c46846adce1598a7af04c
// flow-typed version: <<STUB>>/jest-directory-named-resolver_vjsonnull/jest-directory-named-resolver/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-directory-named-resolver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-directory-named-resolver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-directory-named-resolver/lib/__tests__/resolve.test' {
  declare module.exports: any;
}

declare module 'jest-directory-named-resolver/lib/index' {
  declare module.exports: any;
}

declare module 'jest-directory-named-resolver/tests/file' {
  declare module.exports: any;
}

declare module 'jest-directory-named-resolver/tests/test1/index' {
  declare module.exports: any;
}

declare module 'jest-directory-named-resolver/tests/test1/test1' {
  declare module.exports: any;
}

declare module 'jest-directory-named-resolver/tests/test2/test2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-directory-named-resolver/lib/__tests__/resolve.test.js' {
  declare module.exports: $Exports<'jest-directory-named-resolver/lib/__tests__/resolve.test'>;
}
declare module 'jest-directory-named-resolver/lib/index.js' {
  declare module.exports: $Exports<'jest-directory-named-resolver/lib/index'>;
}
declare module 'jest-directory-named-resolver/tests/file.js' {
  declare module.exports: $Exports<'jest-directory-named-resolver/tests/file'>;
}
declare module 'jest-directory-named-resolver/tests/test1/index.js' {
  declare module.exports: $Exports<'jest-directory-named-resolver/tests/test1/index'>;
}
declare module 'jest-directory-named-resolver/tests/test1/test1.js' {
  declare module.exports: $Exports<'jest-directory-named-resolver/tests/test1/test1'>;
}
declare module 'jest-directory-named-resolver/tests/test2/test2.js' {
  declare module.exports: $Exports<'jest-directory-named-resolver/tests/test2/test2'>;
}
