// flow-typed signature: 902cf0dd4a6150122d23698b4d401c11
// flow-typed version: <<STUB>>/react-onclickoutside_v^6.6.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-onclickoutside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-onclickoutside' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-onclickoutside/dist/react-onclickoutside' {
  declare module.exports: any
}

declare module 'react-onclickoutside/dist/react-onclickoutside.min' {
  declare module.exports: any
}

declare module 'react-onclickoutside/es/detect-passive-events' {
  declare module.exports: any
}

declare module 'react-onclickoutside/es/dom-helpers' {
  declare module.exports: any
}

declare module 'react-onclickoutside/es/index' {
  declare module.exports: any
}

declare module 'react-onclickoutside/es/uid' {
  declare module.exports: any
}

declare module 'react-onclickoutside/lib/detect-passive-events' {
  declare module.exports: any
}

declare module 'react-onclickoutside/lib/dom-helpers' {
  declare module.exports: any
}

declare module 'react-onclickoutside/lib/index' {
  declare module.exports: any
}

declare module 'react-onclickoutside/lib/uid' {
  declare module.exports: any
}

// Filename aliases
declare module 'react-onclickoutside/dist/react-onclickoutside.js' {
  declare module.exports: $Exports<
    'react-onclickoutside/dist/react-onclickoutside'
  >
}
declare module 'react-onclickoutside/dist/react-onclickoutside.min.js' {
  declare module.exports: $Exports<
    'react-onclickoutside/dist/react-onclickoutside.min'
  >
}
declare module 'react-onclickoutside/es/detect-passive-events.js' {
  declare module.exports: $Exports<
    'react-onclickoutside/es/detect-passive-events'
  >
}
declare module 'react-onclickoutside/es/dom-helpers.js' {
  declare module.exports: $Exports<'react-onclickoutside/es/dom-helpers'>
}
declare module 'react-onclickoutside/es/index.js' {
  declare module.exports: $Exports<'react-onclickoutside/es/index'>
}
declare module 'react-onclickoutside/es/uid.js' {
  declare module.exports: $Exports<'react-onclickoutside/es/uid'>
}
declare module 'react-onclickoutside/lib/detect-passive-events.js' {
  declare module.exports: $Exports<
    'react-onclickoutside/lib/detect-passive-events'
  >
}
declare module 'react-onclickoutside/lib/dom-helpers.js' {
  declare module.exports: $Exports<'react-onclickoutside/lib/dom-helpers'>
}
declare module 'react-onclickoutside/lib/index.js' {
  declare module.exports: $Exports<'react-onclickoutside/lib/index'>
}
declare module 'react-onclickoutside/lib/uid.js' {
  declare module.exports: $Exports<'react-onclickoutside/lib/uid'>
}
