// flow-typed signature: 433759527fae2362f833fd38d56632b8
// flow-typed version: <<STUB>>/slugg_v^1.2.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slugg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slugg' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slugg/slugg' {
  declare module.exports: any
}

// Filename aliases
declare module 'slugg/slugg.js' {
  declare module.exports: $Exports<'slugg/slugg'>
}
