// flow-typed signature: f43970941b84841bfa73f9eb1caf2aca
// flow-typed version: <<STUB>>/@firebase/auth_v^0.2.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@firebase/auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@firebase/auth' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@firebase/auth/dist/auth' {
  declare module.exports: any
}

// Filename aliases
declare module '@firebase/auth/dist/auth.js' {
  declare module.exports: $Exports<'@firebase/auth/dist/auth'>
}
