// flow-typed signature: 102df014fdfc511e0d67307f7c1ca339
// flow-typed version: <<STUB>>/@firebase/database_v^0.1.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@firebase/database'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@firebase/database' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@firebase/database/dist/cjs/index' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/index.node' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/api/Database' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/api/DataSnapshot' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/api/internal' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/api/onDisconnect' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/api/Query' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/api/Reference' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/api/test_access' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/api/TransactionResult' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/AuthTokenProvider' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/CompoundWrite' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/operation/AckUserWrite' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/operation/ListenComplete' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/operation/Merge' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/operation/Operation' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/operation/Overwrite' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/PersistentConnection' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/ReadonlyRestClient' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/Repo_transaction' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/Repo' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/RepoInfo' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/RepoManager' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/ServerActions' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/ChildrenNode' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/childSet' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/comparators' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/indexes/Index' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/indexes/KeyIndex' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/indexes/PathIndex' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/indexes/PriorityIndex' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/indexes/ValueIndex' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/IndexMap' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/LeafNode' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/Node' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/nodeFromJSON' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/snap/snap' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/SnapshotHolder' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/SparseSnapshotTree' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/stats/StatsCollection' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/stats/StatsListener' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/stats/StatsManager' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/stats/StatsReporter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/storage/DOMStorageWrapper' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/storage/MemoryStorage' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/storage/storage' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/SyncPoint' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/SyncTree' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/CountedSet' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/EventEmitter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/ImmutableTree' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/libs/parser' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/NextPushId' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/OnlineMonitor' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/Path' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/ServerValues' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/SortedMap' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/Tree' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/util' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/validation' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/util/VisibilityMonitor' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/CacheNode' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/Change' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/ChildChangeAccumulator' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/CompleteChildSource' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/Event' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/EventGenerator' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/EventQueue' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/EventRegistration' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/filter/IndexedFilter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/filter/LimitedFilter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/filter/NodeFilter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/filter/RangedFilter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/QueryParams' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/View' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/ViewCache' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/view/ViewProcessor' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/core/WriteTree' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/nodePatches' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/realtime/BrowserPollConnection' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/realtime/Connection' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/realtime/Constants' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/realtime/polling/PacketReceiver' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/realtime/Transport' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/realtime/TransportManager' {
  declare module.exports: any
}

declare module '@firebase/database/dist/cjs/src/realtime/WebSocketConnection' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/index' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/index.node' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/api/Database' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/api/DataSnapshot' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/api/internal' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/api/onDisconnect' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/api/Query' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/api/Reference' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/api/test_access' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/api/TransactionResult' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/AuthTokenProvider' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/CompoundWrite' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/operation/AckUserWrite' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/operation/ListenComplete' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/operation/Merge' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/operation/Operation' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/operation/Overwrite' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/PersistentConnection' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/ReadonlyRestClient' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/Repo_transaction' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/Repo' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/RepoInfo' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/RepoManager' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/ServerActions' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/ChildrenNode' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/childSet' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/comparators' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/indexes/Index' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/indexes/KeyIndex' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/indexes/PathIndex' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/indexes/PriorityIndex' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/indexes/ValueIndex' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/IndexMap' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/LeafNode' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/Node' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/nodeFromJSON' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/snap/snap' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/SnapshotHolder' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/SparseSnapshotTree' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/stats/StatsCollection' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/stats/StatsListener' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/stats/StatsManager' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/stats/StatsReporter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/storage/DOMStorageWrapper' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/storage/MemoryStorage' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/storage/storage' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/SyncPoint' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/SyncTree' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/CountedSet' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/EventEmitter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/ImmutableTree' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/libs/parser' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/NextPushId' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/OnlineMonitor' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/Path' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/ServerValues' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/SortedMap' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/Tree' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/util' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/validation' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/util/VisibilityMonitor' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/CacheNode' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/Change' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/ChildChangeAccumulator' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/CompleteChildSource' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/Event' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/EventGenerator' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/EventQueue' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/EventRegistration' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/filter/IndexedFilter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/filter/LimitedFilter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/filter/NodeFilter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/filter/RangedFilter' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/QueryParams' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/View' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/ViewCache' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/view/ViewProcessor' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/core/WriteTree' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/nodePatches' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/realtime/BrowserPollConnection' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/realtime/Connection' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/realtime/Constants' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/realtime/polling/PacketReceiver' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/realtime/Transport' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/realtime/TransportManager' {
  declare module.exports: any
}

declare module '@firebase/database/dist/esm/src/realtime/WebSocketConnection' {
  declare module.exports: any
}

// Filename aliases
declare module '@firebase/database/dist/cjs/index.js' {
  declare module.exports: $Exports<'@firebase/database/dist/cjs/index'>
}
declare module '@firebase/database/dist/cjs/index.node.js' {
  declare module.exports: $Exports<'@firebase/database/dist/cjs/index.node'>
}
declare module '@firebase/database/dist/cjs/src/api/Database.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/api/Database'
  >
}
declare module '@firebase/database/dist/cjs/src/api/DataSnapshot.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/api/DataSnapshot'
  >
}
declare module '@firebase/database/dist/cjs/src/api/internal.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/api/internal'
  >
}
declare module '@firebase/database/dist/cjs/src/api/onDisconnect.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/api/onDisconnect'
  >
}
declare module '@firebase/database/dist/cjs/src/api/Query.js' {
  declare module.exports: $Exports<'@firebase/database/dist/cjs/src/api/Query'>
}
declare module '@firebase/database/dist/cjs/src/api/Reference.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/api/Reference'
  >
}
declare module '@firebase/database/dist/cjs/src/api/test_access.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/api/test_access'
  >
}
declare module '@firebase/database/dist/cjs/src/api/TransactionResult.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/api/TransactionResult'
  >
}
declare module '@firebase/database/dist/cjs/src/core/AuthTokenProvider.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/AuthTokenProvider'
  >
}
declare module '@firebase/database/dist/cjs/src/core/CompoundWrite.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/CompoundWrite'
  >
}
declare module '@firebase/database/dist/cjs/src/core/operation/AckUserWrite.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/operation/AckUserWrite'
  >
}
declare module '@firebase/database/dist/cjs/src/core/operation/ListenComplete.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/operation/ListenComplete'
  >
}
declare module '@firebase/database/dist/cjs/src/core/operation/Merge.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/operation/Merge'
  >
}
declare module '@firebase/database/dist/cjs/src/core/operation/Operation.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/operation/Operation'
  >
}
declare module '@firebase/database/dist/cjs/src/core/operation/Overwrite.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/operation/Overwrite'
  >
}
declare module '@firebase/database/dist/cjs/src/core/PersistentConnection.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/PersistentConnection'
  >
}
declare module '@firebase/database/dist/cjs/src/core/ReadonlyRestClient.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/ReadonlyRestClient'
  >
}
declare module '@firebase/database/dist/cjs/src/core/Repo_transaction.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/Repo_transaction'
  >
}
declare module '@firebase/database/dist/cjs/src/core/Repo.js' {
  declare module.exports: $Exports<'@firebase/database/dist/cjs/src/core/Repo'>
}
declare module '@firebase/database/dist/cjs/src/core/RepoInfo.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/RepoInfo'
  >
}
declare module '@firebase/database/dist/cjs/src/core/RepoManager.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/RepoManager'
  >
}
declare module '@firebase/database/dist/cjs/src/core/ServerActions.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/ServerActions'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/ChildrenNode.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/ChildrenNode'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/childSet.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/childSet'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/comparators.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/comparators'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/indexes/Index.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/indexes/Index'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/indexes/KeyIndex.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/indexes/KeyIndex'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/indexes/PathIndex.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/indexes/PathIndex'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/indexes/PriorityIndex.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/indexes/PriorityIndex'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/indexes/ValueIndex.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/indexes/ValueIndex'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/IndexMap.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/IndexMap'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/LeafNode.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/LeafNode'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/Node.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/Node'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/nodeFromJSON.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/nodeFromJSON'
  >
}
declare module '@firebase/database/dist/cjs/src/core/snap/snap.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/snap/snap'
  >
}
declare module '@firebase/database/dist/cjs/src/core/SnapshotHolder.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/SnapshotHolder'
  >
}
declare module '@firebase/database/dist/cjs/src/core/SparseSnapshotTree.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/SparseSnapshotTree'
  >
}
declare module '@firebase/database/dist/cjs/src/core/stats/StatsCollection.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/stats/StatsCollection'
  >
}
declare module '@firebase/database/dist/cjs/src/core/stats/StatsListener.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/stats/StatsListener'
  >
}
declare module '@firebase/database/dist/cjs/src/core/stats/StatsManager.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/stats/StatsManager'
  >
}
declare module '@firebase/database/dist/cjs/src/core/stats/StatsReporter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/stats/StatsReporter'
  >
}
declare module '@firebase/database/dist/cjs/src/core/storage/DOMStorageWrapper.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/storage/DOMStorageWrapper'
  >
}
declare module '@firebase/database/dist/cjs/src/core/storage/MemoryStorage.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/storage/MemoryStorage'
  >
}
declare module '@firebase/database/dist/cjs/src/core/storage/storage.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/storage/storage'
  >
}
declare module '@firebase/database/dist/cjs/src/core/SyncPoint.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/SyncPoint'
  >
}
declare module '@firebase/database/dist/cjs/src/core/SyncTree.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/SyncTree'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/CountedSet.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/CountedSet'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/EventEmitter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/EventEmitter'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/ImmutableTree.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/ImmutableTree'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/libs/parser.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/libs/parser'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/NextPushId.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/NextPushId'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/OnlineMonitor.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/OnlineMonitor'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/Path.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/Path'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/ServerValues.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/ServerValues'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/SortedMap.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/SortedMap'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/Tree.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/Tree'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/util.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/util'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/validation.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/validation'
  >
}
declare module '@firebase/database/dist/cjs/src/core/util/VisibilityMonitor.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/util/VisibilityMonitor'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/CacheNode.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/CacheNode'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/Change.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/Change'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/ChildChangeAccumulator.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/ChildChangeAccumulator'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/CompleteChildSource.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/CompleteChildSource'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/Event.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/Event'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/EventGenerator.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/EventGenerator'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/EventQueue.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/EventQueue'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/EventRegistration.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/EventRegistration'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/filter/IndexedFilter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/filter/IndexedFilter'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/filter/LimitedFilter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/filter/LimitedFilter'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/filter/NodeFilter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/filter/NodeFilter'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/filter/RangedFilter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/filter/RangedFilter'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/QueryParams.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/QueryParams'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/View.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/View'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/ViewCache.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/ViewCache'
  >
}
declare module '@firebase/database/dist/cjs/src/core/view/ViewProcessor.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/view/ViewProcessor'
  >
}
declare module '@firebase/database/dist/cjs/src/core/WriteTree.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/core/WriteTree'
  >
}
declare module '@firebase/database/dist/cjs/src/nodePatches.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/nodePatches'
  >
}
declare module '@firebase/database/dist/cjs/src/realtime/BrowserPollConnection.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/realtime/BrowserPollConnection'
  >
}
declare module '@firebase/database/dist/cjs/src/realtime/Connection.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/realtime/Connection'
  >
}
declare module '@firebase/database/dist/cjs/src/realtime/Constants.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/realtime/Constants'
  >
}
declare module '@firebase/database/dist/cjs/src/realtime/polling/PacketReceiver.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/realtime/polling/PacketReceiver'
  >
}
declare module '@firebase/database/dist/cjs/src/realtime/Transport.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/realtime/Transport'
  >
}
declare module '@firebase/database/dist/cjs/src/realtime/TransportManager.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/realtime/TransportManager'
  >
}
declare module '@firebase/database/dist/cjs/src/realtime/WebSocketConnection.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/cjs/src/realtime/WebSocketConnection'
  >
}
declare module '@firebase/database/dist/esm/index.js' {
  declare module.exports: $Exports<'@firebase/database/dist/esm/index'>
}
declare module '@firebase/database/dist/esm/index.node.js' {
  declare module.exports: $Exports<'@firebase/database/dist/esm/index.node'>
}
declare module '@firebase/database/dist/esm/src/api/Database.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/api/Database'
  >
}
declare module '@firebase/database/dist/esm/src/api/DataSnapshot.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/api/DataSnapshot'
  >
}
declare module '@firebase/database/dist/esm/src/api/internal.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/api/internal'
  >
}
declare module '@firebase/database/dist/esm/src/api/onDisconnect.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/api/onDisconnect'
  >
}
declare module '@firebase/database/dist/esm/src/api/Query.js' {
  declare module.exports: $Exports<'@firebase/database/dist/esm/src/api/Query'>
}
declare module '@firebase/database/dist/esm/src/api/Reference.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/api/Reference'
  >
}
declare module '@firebase/database/dist/esm/src/api/test_access.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/api/test_access'
  >
}
declare module '@firebase/database/dist/esm/src/api/TransactionResult.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/api/TransactionResult'
  >
}
declare module '@firebase/database/dist/esm/src/core/AuthTokenProvider.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/AuthTokenProvider'
  >
}
declare module '@firebase/database/dist/esm/src/core/CompoundWrite.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/CompoundWrite'
  >
}
declare module '@firebase/database/dist/esm/src/core/operation/AckUserWrite.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/operation/AckUserWrite'
  >
}
declare module '@firebase/database/dist/esm/src/core/operation/ListenComplete.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/operation/ListenComplete'
  >
}
declare module '@firebase/database/dist/esm/src/core/operation/Merge.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/operation/Merge'
  >
}
declare module '@firebase/database/dist/esm/src/core/operation/Operation.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/operation/Operation'
  >
}
declare module '@firebase/database/dist/esm/src/core/operation/Overwrite.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/operation/Overwrite'
  >
}
declare module '@firebase/database/dist/esm/src/core/PersistentConnection.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/PersistentConnection'
  >
}
declare module '@firebase/database/dist/esm/src/core/ReadonlyRestClient.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/ReadonlyRestClient'
  >
}
declare module '@firebase/database/dist/esm/src/core/Repo_transaction.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/Repo_transaction'
  >
}
declare module '@firebase/database/dist/esm/src/core/Repo.js' {
  declare module.exports: $Exports<'@firebase/database/dist/esm/src/core/Repo'>
}
declare module '@firebase/database/dist/esm/src/core/RepoInfo.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/RepoInfo'
  >
}
declare module '@firebase/database/dist/esm/src/core/RepoManager.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/RepoManager'
  >
}
declare module '@firebase/database/dist/esm/src/core/ServerActions.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/ServerActions'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/ChildrenNode.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/ChildrenNode'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/childSet.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/childSet'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/comparators.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/comparators'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/indexes/Index.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/indexes/Index'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/indexes/KeyIndex.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/indexes/KeyIndex'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/indexes/PathIndex.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/indexes/PathIndex'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/indexes/PriorityIndex.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/indexes/PriorityIndex'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/indexes/ValueIndex.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/indexes/ValueIndex'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/IndexMap.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/IndexMap'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/LeafNode.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/LeafNode'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/Node.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/Node'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/nodeFromJSON.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/nodeFromJSON'
  >
}
declare module '@firebase/database/dist/esm/src/core/snap/snap.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/snap/snap'
  >
}
declare module '@firebase/database/dist/esm/src/core/SnapshotHolder.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/SnapshotHolder'
  >
}
declare module '@firebase/database/dist/esm/src/core/SparseSnapshotTree.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/SparseSnapshotTree'
  >
}
declare module '@firebase/database/dist/esm/src/core/stats/StatsCollection.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/stats/StatsCollection'
  >
}
declare module '@firebase/database/dist/esm/src/core/stats/StatsListener.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/stats/StatsListener'
  >
}
declare module '@firebase/database/dist/esm/src/core/stats/StatsManager.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/stats/StatsManager'
  >
}
declare module '@firebase/database/dist/esm/src/core/stats/StatsReporter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/stats/StatsReporter'
  >
}
declare module '@firebase/database/dist/esm/src/core/storage/DOMStorageWrapper.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/storage/DOMStorageWrapper'
  >
}
declare module '@firebase/database/dist/esm/src/core/storage/MemoryStorage.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/storage/MemoryStorage'
  >
}
declare module '@firebase/database/dist/esm/src/core/storage/storage.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/storage/storage'
  >
}
declare module '@firebase/database/dist/esm/src/core/SyncPoint.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/SyncPoint'
  >
}
declare module '@firebase/database/dist/esm/src/core/SyncTree.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/SyncTree'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/CountedSet.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/CountedSet'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/EventEmitter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/EventEmitter'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/ImmutableTree.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/ImmutableTree'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/libs/parser.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/libs/parser'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/NextPushId.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/NextPushId'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/OnlineMonitor.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/OnlineMonitor'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/Path.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/Path'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/ServerValues.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/ServerValues'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/SortedMap.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/SortedMap'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/Tree.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/Tree'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/util.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/util'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/validation.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/validation'
  >
}
declare module '@firebase/database/dist/esm/src/core/util/VisibilityMonitor.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/util/VisibilityMonitor'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/CacheNode.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/CacheNode'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/Change.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/Change'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/ChildChangeAccumulator.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/ChildChangeAccumulator'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/CompleteChildSource.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/CompleteChildSource'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/Event.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/Event'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/EventGenerator.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/EventGenerator'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/EventQueue.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/EventQueue'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/EventRegistration.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/EventRegistration'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/filter/IndexedFilter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/filter/IndexedFilter'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/filter/LimitedFilter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/filter/LimitedFilter'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/filter/NodeFilter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/filter/NodeFilter'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/filter/RangedFilter.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/filter/RangedFilter'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/QueryParams.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/QueryParams'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/View.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/View'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/ViewCache.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/ViewCache'
  >
}
declare module '@firebase/database/dist/esm/src/core/view/ViewProcessor.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/view/ViewProcessor'
  >
}
declare module '@firebase/database/dist/esm/src/core/WriteTree.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/core/WriteTree'
  >
}
declare module '@firebase/database/dist/esm/src/nodePatches.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/nodePatches'
  >
}
declare module '@firebase/database/dist/esm/src/realtime/BrowserPollConnection.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/realtime/BrowserPollConnection'
  >
}
declare module '@firebase/database/dist/esm/src/realtime/Connection.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/realtime/Connection'
  >
}
declare module '@firebase/database/dist/esm/src/realtime/Constants.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/realtime/Constants'
  >
}
declare module '@firebase/database/dist/esm/src/realtime/polling/PacketReceiver.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/realtime/polling/PacketReceiver'
  >
}
declare module '@firebase/database/dist/esm/src/realtime/Transport.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/realtime/Transport'
  >
}
declare module '@firebase/database/dist/esm/src/realtime/TransportManager.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/realtime/TransportManager'
  >
}
declare module '@firebase/database/dist/esm/src/realtime/WebSocketConnection.js' {
  declare module.exports: $Exports<
    '@firebase/database/dist/esm/src/realtime/WebSocketConnection'
  >
}
